network:
  adaptor:
    kftc-file:
      cms:
        dataframe: 4100
        enabled: true
        hex-mode: false
        recv-temp-file-path: C:/share/recv
        remote-host: 127.0.0.1
        remote-port: 8000
        send-temp-file-path: C:/share/send
server:
  port: 6701
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  pid:
    file: C:/indigoesb/agent/im/pid/TCP_KFTC_CMS_FILE_01_tmp
