network:
  adaptor:
    tcp-message:
      length:
        bind-ports:
        - 8101
        - 8102
        call-base-path: https://127.0.0.1:6602
        call-type: HTTP
        enabled: true
        extractor:
          message-id: 14
          message-id-len: 10
          work-code: 4
          work-code-len: 10
        hex-mode: false
        initial-bytes-to-strip: 0
        length-adjustment: 0
        length-field-length: 4
        length-field-offset: 0
        logging-base-path: https://127.0.0.1:6800
        logging-task-count: 4
        max-frame-length: 4096
        reconnect-sec: 30
        recv-task-count: 10
        remote-hosts:
        - 127.0.0.1
        - 127.0.0.1
        remote-ports:
        - 8001
        - 8002
        request-usage-size: 10000
        request-wait-time-out-sec: 60
        src-org: S001
        string-value-use: true
        trg-org: KFTC
server:
  port: 6702
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  pid:
    file: C:/mesim_mci/im/pid/TCP_LENGTH_MSG_01_tmp
interface-id:
  '0210300001': TCP_KFTC_00002
  '0210300002': TCP_KFTC_00004
  '0210300003': TCP_KFTC_00006
  '0210300004': TCP_KFTC_00008
  '0210300005': TCP_KFTC_00010
product:
  authId: metabuild
  authPassword: ENC(jUZV7x/Gvtdp3fuVkf2Zi2kll8Roso/E742QqUdsnYG3I06aZspyWgc+ZZpSGSj2)
server:
  ssl:
    key-alias: spring
    key-store: classpath:keystore.p12
    key-store-password: ENC(jUZV7x/Gvtdp3fuVkf2Zi2kll8Roso/E742QqUdsnYG3I06aZspyWgc+ZZpSGSj2)
    key-store-type: PKCS12
  tomcat:
    max-http-post-size: 100000000
    max-swallow-size: 100000000

